### ISSUE TITLE
pkg downloaded via pip errors

### ISSUE THREAD

**Issue by codercahol** [murraycutforth/segment-multiwell-plate#1]
I get the error:
```
line 256, in _grid_crop
    subcell_images = map(resample_fn, image)
    img_array[i, j] = np.squeeze(np.array(subcell_images))  # Squeeze used to reduce dimensionality if input is 2D
    ~~~~~~~~~^^^^^^
TypeError: float() argument must be a string or a real number, not 'map'
```

when I run the package downloaded via pip.

The github code has been modified to fix the error:
`subcell_images = list(map(resample_fn, image))`
but the pypi package is not working

**Comment by murraycutforth** [comment]
Ah yes my bad, I see that you've altered the poetry.toml to track the github repo which hopefully fixes this? I'll also update the pip package though since I've made other improvements since then.

**Comment by murraycutforth** [comment]
I've put a new version, 0.3, on pip now which fixes this. Thanks for the heads up!
